<?php // app/views/partials/sidebar.phtml 
?>
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<?= URL_BASE ?>/home">
        <div class="sidebar-brand-icon">
            <i class="fas fa-heartbeat"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Clínica Assista</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" href="<?= URL_BASE ?>/home">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Painel de Controle</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <div class="sidebar-heading">
        Tokens
    </div>

    <li class="nav-item">
        <a class="nav-link" href="<?= URL_BASE ?>/gerar-token">
            <i class="fas fa-fw fa-plus-circle"></i>
            <span>Novo Token</span></a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="<?= URL_BASE ?>/meus-tokens">
            <i class="fas fa-fw fa-history"></i>
            <span>Histórico</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <div class="sidebar-heading">
        Cadastros
    </div>

    <li class="nav-item">
        <a class="nav-link" href="<?= URL_BASE ?>/pacientes/cadastrar">
            <i class="fas fa-fw fa-user-injured"></i>
            <span>Pacientes</span></a>
    </li>

    <!-- Nav Item - Meus Pacientes (NOVO) -->
    <li class="nav-item">
        <a class="nav-link" href="<?= defined('URL_BASE') ? URL_BASE : '' ?>/pacientes">
            <i class="fas fa-fw fa-user-injured"></i>
            <span>Meus Pacientes</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
    <div class="sidebar-heading">
        Relatórios Gerais
    </div>

    <!-- NOVO ITEM: RELATÓRIOS -->
    <li class="nav-item">
        <a class="nav-link" href="<?= URL_BASE ?>/relatorios">
            <i class="fas fa-fw fa-chart-bar"></i>
            <span>Relatórios Financeiros</span></a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="<?= URL_BASE ?>/relatorios/quantitativo">
            <i class="fas fa-fw fa-chart-pie"></i>
            <span>Relatório Quantitativo</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>